name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  - main

variables:
  python.version: '3.9'
  config.file: 'config.yaml'  # Update to your config path

pool:
  vmImage: ubuntu-latest

stages:
  - stage: validate_uc_config
    displayName: "Validate Unity Catalog Config"
    jobs:
      - job: validate
        displayName: "Run Config Validator"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.10'
              addToPath: true

          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            displayName: 'Install Python dependencies'

          - script: |
              echo "Reading workspace_url from terraform.tfvars..."
              CONFIG_DIR="${{ parameters.cloudEnvironment }}/${{ parameters.region }}/${{ parameters.workSpaceId }}"
              TFVARS_PATH="$CONFIG_DIR/terraform.tfvars"

              if [ ! -f "$TFVARS_PATH" ]; then
                echo "Error: terraform.tfvars not found at $TFVARS_PATH"
                exit 1
              fi

              WORKSPACE_URL=$(grep -oP 'workspace_url\s*=\s*"\K[^"]+' "$TFVARS_PATH")
              echo "Extracted workspace_url: $WORKSPACE_URL"

              echo "Running UC config validation..."
              python validate_uc_config.py \
                --config_dir "$CONFIG_DIR" \
                --workspace_url "$WORKSPACE_URL" \
                --subscription_id "${{ parameters.deploymentSubscriptionId }}"
            displayName: 'Validate UC Configuration'
